databases:
  - name: students_performance_db
    databaseName: students_performance
    user: students_performance_user
    plan: free

services:
  - type: web
    name: students-performance-system
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn students_performance.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

      - key: DATABASE_URL
        fromDatabase:
          name: students_performance_db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: DJANGO_SETTINGS_MODULE
        value: students_performance.production_settings

      - key: DEBUG
        value: "False"
